---
title: "Untitled"
output: html_document
date: "2023-10-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  read the data in

```{r}
library(tidyverse)
library(here)
library(sf)
report <- read_csv(here::here("Wk4 Homework",  "HDR21-22_Composite_indices_complete_time_series.csv"),
                   na="NULL")
shape <- st_read(here::here("Wk4 Homework", "World_Countries_Generalized", "World_Countries_Generalized.shp"))
```

2.  filter the data in report

```{r}
library(dplyr)
library(janitor)
library(stringr)
report1 <- report %>%
  clean_names(.) %>%
  dplyr::rename(giirank_2021='gii_rank_2021') %>%
  dplyr::select(iso3, country, hdicode, region, starts_with("gii_"))
```

# Here we select all the columns related with gii except the ranking, but we may only need gii_2019 and gii_2010.

3.  create a new column

```{r}
final <- report1 %>%
  mutate(diff_2010_19 = gii_2019 - gii_2010)
```

# We can use countrycode package here to mutate a new column to match country with iso2 and left join by the code.

4.  left_join

```{r}
joined_data <- shape %>%
  clean_names(.)%>%
  left_join(.,
            final,
            by = c("country" = "country"))
```

5.  map \# no need to map

```{r}
library(tmap)
library(tmaptools)
# method 1
tmap_mode("plot")
qtm(joined_data, 
    fill = "diff_2010_19")
```

